### PR TITLE
✨ added support for uploading pre-generated zip file

### LINKED ISSUE #1: Compile assets before uploading
My theme needs to build assets before uploading. It would be nice to add an option to run gulp/webpack whatever or, as an alternative, accept an existing zip file instead of creating one.

### PR DESCRIPTION
**Pull request by vikaspotluri123**
closes #1

- Add a new `file` option which uploads the specified file instead of generating one

### CODE REVIEW

**Comment by nextwebb** [comment]
hi i'm new to Ghost. i'll like to be a contributor to Ghost CMS . how do i get started?

**Comment by vikaspotluri123** [comment]
Hey @nextwebb :wave: I think the best starting point is the [Ghost Contribution docs](https://ghost.org/docs/concepts/contributing/) 😄

**Comment by davisonio** [comment]
Hey guys can we get this merged in? Would be super useful for my workflow.

**Comment by pitscher** [comment]
I know the ghost team is busy with some CVE stuff going on...
But it would be nice to have this feature in place. :)

Maybe @kevinansfield or @ErisDS can review this request. (I saw you as participants in some related conversations out there :D )
To get things done quickly I would be very happy if someone could provide a little intro how to implement this feature in an actions workflow.
For a theme deployment the steps would be:
New theme code -> test with gscan -> build theme (I used "gulp zip") -> deploy (with this action)

**Comment by daniellockyer** [comment]
Thanks @vikaspotluri123! :grinning:

**Comment by daniellockyer** [comment]
This was shipped in 1.3.0 :slightly_smiling_face:

**Pull request merged**
